/* eslint-disable */
import { RouterModule, Routes } from '@angular/router';
import { AdministrationComponent } from './components/administration.component';
import { SharedModule } from '../shared/components/shared.module';
import { DropdownModule } from 'primeng/primeng';
import { FileUploadModule } from 'primeng/primeng';
import { InputTextModule } from 'primeng/primeng';
import { TooltipModule } from 'primeng/primeng';
import { PanelModule } from 'primeng/primeng';
import { BreadcrumbModule } from 'primeng/primeng';
import { InputTextareaModule } from 'primeng/primeng';
import { AutoCompleteModule } from 'primeng/primeng';
import { InputSwitchModule } from 'primeng/primeng';
import { OverlayPanelModule } from 'primeng/primeng';
import { ProgressSpinnerModule } from 'primeng/primeng';
import { MessageModule } from 'primeng/primeng';
import { CheckboxModule } from 'primeng/primeng';
import { TreeModule } from 'primeng/primeng';
import { ToggleButtonModule } from 'primeng/primeng';
import { AdministrationGuard } from './guards/administration.guard';
import { AdministrationService } from './services/administration.service';
