name: PUBLISH
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: npm ci
    - name: Archive Production Artifact
      uses: actions/upload-artifact@master
      with:
        name: primeng-import-migrate
        path: dist
