name: PUBLISH
on:
  push:
    branches: [ master ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: npm ci
    - name: Production Build
      run: npm run build
    - name: Archive Production Artifact
      uses: actions/upload-artifact@master
      with:
        name: primeng-import-migrate
        path: dist
    - name: Login
      run: npm run login
    - name: Publish Artifact
      run: npm publish
